name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string
jobs:
  # dev-deploy job
  integration-test:
        needs: dev-deploy
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          ingress-url: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}